name: Docker - Dist-Tests


on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'docker/**'
      - '!docker/deploy.*'
      - '.github/**'
      - '!.github/workflows/docker-dist-tests.yml'
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: codex-storage/github-actions/.github/workflows/docker-reusable.yml@master
    with:
      docker_file: docker/deploy.Dockerfile
      dockerhub_repo: codexstorage/codex-contracts-eth
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
      tag_suffix: dist-tests
    secrets: inherit
