name: Docker - Dist-Tests


on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'docker/**'
      - '!docker/deploy.*'
      - '.github/**'
      - '!.github/workflows/docker-dist-tests.yml'
      - '!.github/workflows/docker-reusable.yml'
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: ./.github/workflows/docker-reusable.yml
    with:
      docker_file: docker/deploy.Dockerfile
      tag_suffix: dist-tests
    secrets: inherit
